# Generated by Django 5.1.2 on 2025-11-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_imagem'),
        ('produtos', '0004_alter_produto_imagem_carrinhodecompras_and_more'),
    ]

    operations = [
    ]
