"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()  # pega as variáveis do arquivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# url para servir arquivos de mídia
MEDIA_URL = '/media/'
#pasta onde os arquivos de mídia serão salvos
MEDIA_ROOT = BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%$hbnpm1-x-&+cs76_4e-jchn2tvuwf901i&hq8$8t)6=gxi1q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.app.github.dev',
    'https://*.githubpreview.dev',
    'https://scaling-space-garbanzo-976xwjq4qxrp2xxx7-8000.app.github.dev',
    'https://zany-goggles-94w6qq9v55g2w55-8000.app.github.dev',
    'https://paranormal-incantation-rvw7rrg979jcxvqr-8000.app.github.dev',
    'https://urban-guacamole-97669rr7vjjw3757w-8000.app.github.dev',
    'http://localhost:8000',
    'https://localhost:8000'
]

# Configurações de CSRF para ambientes de desenvolvimento (GitHub Codespaces)
# Ajustado para funcionar corretamente com Codespaces
CSRF_COOKIE_SECURE = False  # Desabilitado para desenvolvimento
CSRF_COOKIE_HTTPONLY = False  # Permite JavaScript acessar o token
CSRF_COOKIE_SAMESITE = 'Lax'  # Lax é mais compatível com Codespaces
CSRF_USE_SESSIONS = False  # Usa cookie em vez de sessão para evitar problemas após logout
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_AGE = 31449600  # 1 ano
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_FAILURE_VIEW = 'app.error_views.csrf_failure'
SESSION_COOKIE_SECURE = False  # Desabilitado para desenvolvimento
SESSION_COOKIE_SAMESITE = 'Lax'  # Lax é mais compatível
SESSION_COOKIE_AGE = 1209600  # 2 semanas
SESSION_SAVE_EVERY_REQUEST = True  # Salva sessão em cada request

# Para desenvolvimento, aceita CSRF token do referer
CSRF_COOKIE_PATH = '/'

# Application definition

INSTALLED_APPS = [
    "produtos",
    "users",
    "pets",
    "panel",
    "consultas",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Forçar uso de HTTPS e do domínio correto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

SITE_ID = 1

# Configurações de autenticação e redirecionamento
LOGIN_URL = '/users/login/'  # URL para onde redireciona quando não autenticado
LOGIN_REDIRECT_URL = '/'  # URL após login bem-sucedido
LOGOUT_REDIRECT_URL = '/'  # URL após logout

# Configurações do allauth (se usado)
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
ACCOUNT_LOGOUT_ON_GET = True

# Configuração adicional para CSRF em ambiente de desenvolvimento
if DEBUG:
    # Em desenvolvimento, aceita qualquer origem
    CSRF_TRUSTED_ORIGINS.extend([
        'http://*',
        'https://*'
    ])
    # Desabilita verificação estrita de referer em desenvolvimento
    CSRF_COOKIE_DOMAIN = None

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "app.middleware.CSRFRefreshMiddleware",  # Middleware customizado para CSRF
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'app' / 'templates'],  # Templates do app principal
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
