# Generated by Django 5.1.2 on 2025-11-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_user_type_and_veterinario_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, help_text='Matrícula do funcionário (6 dígitos com prefixo: 10-Vet, 15-Gerente, 20-Supervisor, 25-Func)', max_length=6, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('FUNCIONARIO', 'Funcionário'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente'), ('VETERINARIO', 'Veterinário')], default='CLIENTE', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
